server:
    port: 8090
    tomcat:
        uri-encoding: UTF-8
jsoso:
    token: 600
spring:

    http:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        tomcat:
            default-transaction-isolation: 2
            initial-size: 5
            max-active: 50
            max-idle: 10
            max-wait: 10000
        url: jdbc:mysql://106.14.7.24:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
    devtools:
        restart:
            additional-paths: src/main/java
            enabled: true
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
    redis:
        database: 0
        host: 106.14.7.24
        jedis:
            pool:
                max-active: 50
                max-idle: 50
                max-wait: 2000
                min-idle: 50
        password: 123456
        port: 6379
        timeout: 500
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
    mail:
        host: smtp.163.com
        password: zhangkai0515
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        port: 465
                    starttls:
                        enable: true
                        required: true
        username: sfpy_zk@163.com
system:
    filepath: E:\workspace\images
    #windows下用这个filepath: D:\temp\upload   linux :/vdb1/xxx/vue/resources
    urlpath: http://127.0.0.1:8090/uploadImg/
